# Dracula color palette as fish variables
set -g dracula_background "#282a36"
set -g dracula_current_line "#44475a"
set -g dracula_foreground "#f8f8f2"
set -g dracula_comment "#6272a4"
set -g dracula_cyan "#8be9fd"
set -g dracula_green "#50fa7b"
set -g dracula_orange "#ffb86c"
set -g dracula_pink "#ff79c6"
set -g dracula_purple "#bd93f9"
set -g dracula_red "#ff5555"
set -g dracula_yellow "#f1fa8c"
