format = """
$username\
$hostname\
$directory\
$git_branch\
$git_status\
$python\
$nodejs\
$rust\
$golang\
$character"""

[palettes.dracula]
background   = "#282a36"
current_line = "#44475a"
foreground   = "#f8f8f2"
comment      = "#6272a4"
cyan         = "#8be9fd"
green        = "#50fa7b"
orange       = "#ffb86c"
pink         = "#ff79c6"
purple       = "#bd93f9"
red          = "#ff5555"
yellow       = "#f1fa8c"

palette = "dracula"

[username]
format      = "[$user]($style)"
style_user  = "bold purple"
style_root  = "bold red"
show_always = true

[hostname]
format   = "[@$hostname]($style) "
style    = "bold purple"
ssh_only = false
trim_at  = "."

[directory]
format            = "[ $path]($style) "
style             = "bold cyan"
truncation_length = 3
truncate_to_repo  = false
read_only         = " 󰌾"
read_only_style   = "red"

[git_branch]
format = "[ $branch]($style)"
style  = "bold green"

[git_status]
format    = "[$all_status$ahead_behind]($style) "
style     = "bold green"
ahead     = "⇡${count}"
behind    = "⇣${count}"
diverged  = "⇕⇡${ahead_count}⇣${behind_count}"
modified  = "!${count}"
staged    = "+${count}"
untracked = "?${count}"
deleted   = "✘${count}"

[python]
format = "[ $virtualenv]($style) "
style  = "bold yellow"

[nodejs]
format = "[ $version]($style) "
style  = "bold green"

[rust]
format = "[ $version]($style) "
style  = "bold orange"

[golang]
format = "[ $version]($style) "
style  = "bold cyan"

[cmd_duration]
format   = "[ $duration]($style) "
style    = "bold yellow"
min_time = 2000

[character]
format         = "$symbol "
success_symbol = "[❯](bold green)"
error_symbol   = "[❯](bold red)"
